# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1fe61a00360ab82203f2fa576fbf1bb946e6ed9abe74fe95cef670ff762aa2de486b4b485b94d8b85227ec90f2a65939d9d92928e4cc0111f83a8146c73a973

test:
  secret_key_base: 6ed3ae92bd680f1a3e3eda7d129af72eb30751420eb8e4c663acc043ef2534f7fce953f4fcda20f5c1698906f57dc542d7d4dc8c32b85b97a385b061b9c64ab5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
